/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as IndexRouteImport } from './pages/index'
import { Route as ListUsersRouteImport } from './pages/list/users'
import { Route as ListTicketsRouteImport } from './pages/list/tickets'
import { Route as ListPersonsRouteImport } from './pages/list/persons'
import { Route as ListEventsRouteImport } from './pages/list/events'
import { Route as ListCompanyRouteImport } from './pages/list/company'
import { Route as AuthSignInRouteImport } from './pages/_auth/sign-in'
import { Route as AuthLoginRouteImport } from './pages/_auth/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListUsersRoute = ListUsersRouteImport.update({
  id: '/list/users',
  path: '/list/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ListTicketsRoute = ListTicketsRouteImport.update({
  id: '/list/tickets',
  path: '/list/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ListPersonsRoute = ListPersonsRouteImport.update({
  id: '/list/persons',
  path: '/list/persons',
  getParentRoute: () => rootRouteImport,
} as any)
const ListEventsRoute = ListEventsRouteImport.update({
  id: '/list/events',
  path: '/list/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ListCompanyRoute = ListCompanyRouteImport.update({
  id: '/list/company',
  path: '/list/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/sign-in': typeof AuthSignInRoute
  '/list/company': typeof ListCompanyRoute
  '/list/events': typeof ListEventsRoute
  '/list/persons': typeof ListPersonsRoute
  '/list/tickets': typeof ListTicketsRoute
  '/list/users': typeof ListUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/sign-in': typeof AuthSignInRoute
  '/list/company': typeof ListCompanyRoute
  '/list/events': typeof ListEventsRoute
  '/list/persons': typeof ListPersonsRoute
  '/list/tickets': typeof ListTicketsRoute
  '/list/users': typeof ListUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/list/company': typeof ListCompanyRoute
  '/list/events': typeof ListEventsRoute
  '/list/persons': typeof ListPersonsRoute
  '/list/tickets': typeof ListTicketsRoute
  '/list/users': typeof ListUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sign-in'
    | '/list/company'
    | '/list/events'
    | '/list/persons'
    | '/list/tickets'
    | '/list/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sign-in'
    | '/list/company'
    | '/list/events'
    | '/list/persons'
    | '/list/tickets'
    | '/list/users'
  id:
    | '__root__'
    | '/'
    | '/_auth/login'
    | '/_auth/sign-in'
    | '/list/company'
    | '/list/events'
    | '/list/persons'
    | '/list/tickets'
    | '/list/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignInRoute: typeof AuthSignInRoute
  ListCompanyRoute: typeof ListCompanyRoute
  ListEventsRoute: typeof ListEventsRoute
  ListPersonsRoute: typeof ListPersonsRoute
  ListTicketsRoute: typeof ListTicketsRoute
  ListUsersRoute: typeof ListUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/users': {
      id: '/list/users'
      path: '/list/users'
      fullPath: '/list/users'
      preLoaderRoute: typeof ListUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/tickets': {
      id: '/list/tickets'
      path: '/list/tickets'
      fullPath: '/list/tickets'
      preLoaderRoute: typeof ListTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/persons': {
      id: '/list/persons'
      path: '/list/persons'
      fullPath: '/list/persons'
      preLoaderRoute: typeof ListPersonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/events': {
      id: '/list/events'
      path: '/list/events'
      fullPath: '/list/events'
      preLoaderRoute: typeof ListEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/company': {
      id: '/list/company'
      path: '/list/company'
      fullPath: '/list/company'
      preLoaderRoute: typeof ListCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignInRoute: AuthSignInRoute,
  ListCompanyRoute: ListCompanyRoute,
  ListEventsRoute: ListEventsRoute,
  ListPersonsRoute: ListPersonsRoute,
  ListTicketsRoute: ListTicketsRoute,
  ListUsersRoute: ListUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
